# fly.toml app configuration file generated for how2club on 2023-09-19T20:33:59+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "how2club"
primary_region = "syd"

[build]
  image = "aarondalao/how2club:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  Cloudinary__ApiKey = "129783968236619"
  Cloudinary__CloudName = "dmnofpv0p"
  Sendgrid__User="testEmailSender1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
